[package]
name = "hello_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { git = "https://github.com/spartucus/risc0", branch = "pub-verifier", default-features = false, features = ['std'] }
